version: '3.4'

services:
  db:
    image: restwithaspnet5-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - 3308:3306
    networks:
      - restwithaspnet5-network
  restwithaspnet5:
    image: restwithaspnet5-app
    build:
      context: .
      dockerfile: RestWithASPNET5/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIROMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - restwithaspnet5-network

networks:
  restwithaspnet5-network:
    driver: bridge