sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 5.0
services: docker
before_instal:
  - RestWithASP-NET5/
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag restwithaspnet5-db:latest $DOCKER_USERNAME/restwithaspnet5-db:$TRAVIS_JOB_ID;
    docker tag restwithaspnet5-app:dev $DOCKER_USERNAME/restwithaspnet5-app:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/restwithaspnet5-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/restwithaspnet5-app:$TRAVIS_JOB_ID;
  on:
    branch: main
notifications:
  email: false